### ISSUE TITLE
v2.1.1 development

### ISSUE THREAD

**Issue by sethsandaru** [sethsandaru/vue-form-builder#88]
## Features
- [x] #85 disable specific control(s) 
- [x] Server-side validation
- [x] #83 Read-only Form (show data without form-control - like a preview mode)
- [x] #90 `type='password'` configuration for Text Input control

## Bugs
Dunno, let's see

**Comment by sethsandaru** [comment]
## How server-side validation should work?

### Configuration
- In `Form Configurations`: enable and add your API Endpoint

### How it works
- Make a **POST** Request together with the Form Values to the configured API Endpoint

#### Request
```javascript
fetch('<API_ENDPOINT', {
    data: {
        formValues: {/** your form values **/}
    }
});
```

#### Response if has errors
```javascript
{
    "field-name": string|Array<String>, // fieldName is configured in Vue Form Builder, value should be the error message
}
```

#### Response if no error
An empty JSON response should be good enough:

```javascript
{}
```

or:

```javascript
{
    "isOk": true
}
```

**Comment by sethsandaru** [comment]
@abhimanusharma I have a question regarding the Server-side Validation behaviour. Do you think is it a good idea to show a loading screen while the form doing the XHR request? Or it would be better if the form can disable the button after users pressed it?

**Comment by abhimanusharma** [comment]
@sethsandaru Actually, I use both. I show a loader on the button and make it disable while the response is being retrieving by the XHR request. This gives a clear idea why the button is disabled and what is happening in the application also user can also see when the button is going to enable again, its when the loader will stop loading.

**Comment by sethsandaru** [comment]
@abhimanusharma That's cool, thanks for sharing!

**Comment by sethsandaru** [comment]
On going for the last one - Read-only Form.
